# Generated by Django 2.2.7 on 2019-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mlcmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='/images')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
