# Generated by Django 3.0.2 on 2020-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlcmp',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mlcmp',
            name='platform_name',
            field=models.CharField(choices=[('einstein', 'Salesforce Einstein'), ('watson', 'IBM WATSON')], max_length=100),
        ),
    ]
