# Generated by Django 3.0.3 on 2020-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcmp', '0003_auto_20200208_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlcmp',
            name='result',
            field=models.TextField(blank=True, max_length=555),
        ),
    ]
