# Generated by Django 3.0.3 on 2020-03-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcmp', '0004_auto_20200214_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlcmp',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='mlcmp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
